services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/povs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_LD_CLIENT_SDK_ID=${NEXT_PUBLIC_LD_CLIENT_SDK_ID}
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env.docker
    depends_on:
      server:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge