services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=production
      - PORT=3000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_LD_CLIENT_SDK_ID=${NEXT_PUBLIC_LD_CLIENT_SDK_ID}
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    depends_on:
      - server